<?php include('header.php');?>
<?php
include_once("email.php");
if(isset($_POST['savefeed']))
{
	$empname = $_POST['empname'];
	$empid = $_POST['empid'];
	$empro = $_POST['empro'];
	$empsubpro = $_POST['empsubpro'];
	$empmobile = "Quick Feedback";
	$agenthead = "Quick Feedback";
	$rating = $_POST['rating'];
	$against = $_POST['against'];
	$details = $_POST['feedback'];

	$feedsql = "INSERT INTO feedback_content(employee_id, employee_name, employee_pro, empoyee_sub_pro, employee_mobile, employee_head, feedback_for, feedback_subject, feedback_text, feedback_status) VALUES ('$empid','$empname','$empro','$empsubpro','$empmobile','$rating','$against','$against','$details','$feedstatus')";
	$feedres = mysqli_query($conn, $feedsql);

	$mail->Subject = '360 Quick Feedback | '.$against;
	$mail->Body.= 'Hi, <br><br>';
	$mail->Body.= 'This mail autogenerated by 360 Feedback Portal. <br><br>';
	$mail->Body.= 'Employee Name : '.$empname.'<br>';
	$mail->Body.= 'Employee ID : '.$empid.'<br>';
	$mail->Body.= 'Process : '.$empro.'<br>';
	$mail->Body.= 'Sub Process : '.$empsubpro.'<br>';
	$mail->Body.= 'Head : '.$agenthead.'<br>';
	$mail->Body.= 'Feedback For : '.$against.'<br>';
	
	$mail->Body.= 'Message : '.$details;
	
	$mail->Body.= '<br><br> -----End ----- 360 Feedback!';
	$mail->send();
	if($feedres == true)
	{
		header('Location:thank-you.php');
	}

}
?>
<section class="login-blk">
	<div class="tringle"></div>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="login-aread">
					<div class="row">
						<div class="col-lg-6">
							<div class="signin-blk">
								<h2>WELCOME TO <span style="color:#383838;">360-FEEDBACK</span></h2>
								<p>This portal has been created for your help. You can give any kind of information related to the company. Any kind of degradation is happening or you want to give some suggestive. Your opinion will be heard for any kind of information.</p>
								<p><small><em>* You are free to give your information. Your Id information will be kept secret.</em></small></p>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="quick-feedback">
								<form class="" method="POST" action="" oninput="result.value = slider.value">
									<div class="form-group">
										<label>Your Full Name</label>
										<input type="text" class="form-control" name="empname" required>
									</div>
									<div class="form-group">
										<label>Your Employee ID</label>
										<input type="text" class="form-control" name="empid" required>
									</div>
									<div class="form-group">
										<label>Process</label>
										<input type="text" class="form-control" name="empro" required>
									</div>
									<div class="form-group row">
										<div class="col-lg-6 col-md-6">
											<label>Sub Process <small>(Optional)</small></label>
											<input type="text" class="form-control" name="empsubpro">
										</div>
										<div class="col-lg-6 col-md-6">
											<label>Feedback Star Rating</label>
											<input max="5" step="0.5" type="range" value="1" id="slider" name="rating">
											You Selected <output name="result" for="slider" class="badge badge-danger">1</output>
										</div>

										
									</div>
									<div class="form-group">
										<label>Feedback against:</label>
										<input type="text" class="form-control" name="against" required>
									</div>
									<div class="form-group">
										<label>Feedback details:</label>
										<textarea name="feedback" class="form-control"></textarea>
									</div>
									<div class="form-group">
										<input type="submit" name="savefeed" value="Save Feedback" class="btn btn-dark">
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
	
</section>




	<script src="assets/main.js"></script>
  <script src="assets/popup.js"></script>
  <script src="assets/bootstrap.js"></script>
</body>
</html>